#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
python -u predict.py/predict_inceptionV3.py "$@"

# The previous version of this file was commented-out and follows below:
#
# python -u predict.py/predict_xception.py "$@"
# 
